/* Generated by Nim Compiler v1.6.0 */
/* Compiled for: Any, arm, gcc */
/* Command for C compiler:
   arm-none-eabi-gcc -c  -w -fmax-errors=3 -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F3 -DDEBUG -DSTM32F303RETx -DNUCLEO_F303RE -c -I../Inc -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb   -I/home/rad/.choosenim/toolchains/nim-1.6.0/lib -I/home/rad/nimbedded/bbstrap -o /home/rad/nimbedded/bbstrap/ccode/@mbblink.nim.c.o /home/rad/nimbedded/bbstrap/ccode/@mbblink.nim.c */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_RCC_TypeDef__S8rP7rXCVJEQ3ZO1P7d8UA tyObject_RCC_TypeDef__S8rP7rXCVJEQ3ZO1P7d8UA;
typedef struct tyObject_GPIO_TypeDef__c4Pdem4Qb0EYT3OA5uGJiw tyObject_GPIO_TypeDef__c4Pdem4Qb0EYT3OA5uGJiw;
struct tyObject_RCC_TypeDef__S8rP7rXCVJEQ3ZO1P7d8UA {
NU32 CR;
NU32 CFGR;
NU32 CIR;
NU32 APB2RSTR;
NU32 APB1RSTR;
NU32 AHBENR;
NU32 APB2ENR;
NU32 APB1ENR;
NU32 BDCR;
NU32 CSR;
NU32 AHBRSTR;
NU32 CFGR2;
NU32 CFGR3;
};
struct tyObject_GPIO_TypeDef__c4Pdem4Qb0EYT3OA5uGJiw {
NU32 MODER;
NU32 OTYPER;
NU32 OSPEEDR;
NU32 PUPDR;
NU32 IDR;
NU32 ODR;
NU32 BSRR;
NU32 LCKR;
NU32 AFRL;
NU32 AFRH;
NU32 BRR;
};
N_LIB_PRIVATE N_NIMCALL(void, initLed_bblink_67)(void);
N_LIB_PRIVATE N_NIMCALL(void, go_bblink_103)(void) __attribute__((noreturn));
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
N_LIB_PRIVATE N_NIMCALL(void, initLed_bblink_67)(void) {
	NU32 resX60gensym2_;
	NU32 resX60gensym7_;
	NU32 resX60gensym12_;
	resX60gensym2_ = (NU32)0;
	resX60gensym2_ = (*(NU32 volatile*)(&(*((tyObject_RCC_TypeDef__S8rP7rXCVJEQ3ZO1P7d8UA*) 1073876992)).AHBENR));
	*((NU32 volatile*)((&(*((tyObject_RCC_TypeDef__S8rP7rXCVJEQ3ZO1P7d8UA*) 1073876992)).AHBENR))) = ((NU32) ((NU32)(resX60gensym2_ | ((NU32) (((NU32) 131072))))));
	resX60gensym7_ = (NU32)0;
	resX60gensym7_ = (*(NU32 volatile*)(&(*((tyObject_GPIO_TypeDef__c4Pdem4Qb0EYT3OA5uGJiw*) 1207959552)).MODER));
	*((NU32 volatile*)((&(*((tyObject_GPIO_TypeDef__c4Pdem4Qb0EYT3OA5uGJiw*) 1207959552)).MODER))) = ((NU32) ((NU32)(resX60gensym7_ | ((NU32) (((NI) 1024))))));
	resX60gensym12_ = (NU32)0;
	resX60gensym12_ = (*(NU32 volatile*)(&(*((tyObject_GPIO_TypeDef__c4Pdem4Qb0EYT3OA5uGJiw*) 1207959552)).MODER));
	*((NU32 volatile*)((&(*((tyObject_GPIO_TypeDef__c4Pdem4Qb0EYT3OA5uGJiw*) 1207959552)).MODER))) = ((NU32) ((NU32)(resX60gensym12_ & (NU32)((NU32) ~(((NU32) (((NI) 2048))))))));
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) - (NU32)(((NU) (b))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(r ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(r ^ (NI)((NU32) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		(*res) = r;
	}
	goto LA1_;
	LA5_: ;
	{
		result = NIM_TRUE;
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, go_bblink_103)(void) {
	NI volatile i;
	i = ((NI) 47000);
	{
		while (1) {
			NU32 resX60gensym18_;
			{
				while (1) {
					NI TM__7Re5RxC5bUv9a9bdJV9a6u9c8A_2;
					if (!!((i == ((NI) 0)))) goto LA4;
					if (nimSubInt(i, ((NI) 1), &TM__7Re5RxC5bUv9a9bdJV9a6u9c8A_2)) { raiseOverflow(); };
					i = (NI)(TM__7Re5RxC5bUv9a9bdJV9a6u9c8A_2);
				} LA4: ;
			}
			i = ((NI) 64000);
			resX60gensym18_ = (NU32)0;
			resX60gensym18_ = (*(NU32 volatile*)(&(*((tyObject_GPIO_TypeDef__c4Pdem4Qb0EYT3OA5uGJiw*) 1207959552)).ODR));
			*((NU32 volatile*)((&(*((tyObject_GPIO_TypeDef__c4Pdem4Qb0EYT3OA5uGJiw*) 1207959552)).ODR))) = ((NU32) ((NU32)(resX60gensym18_ ^ ((NU32) (((NI) 32))))));
		}
	}
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	systemDatInit000();
	systemInit000();
	(*inner)();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	initLed_bblink_67();
	go_bblink_103();
}
}

