/* Generated by Nim Compiler v1.6.0 */
/* Compiled for: Any, arm, gcc */
/* Command for C compiler:
   arm-none-eabi-gcc -c  -w -fmax-errors=3 -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F3 -DDEBUG -DSTM32F303RETx -DNUCLEO_F303RE -c -I../Inc -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb   -I/home/rad/.choosenim/toolchains/nim-1.6.0/lib -I/home/rad/nimbedded/bbstrap -o /home/rad/nimbedded/bbstrap/ccode/stdlib_system.nim.c.o /home/rad/nimbedded/bbstrap/ccode/stdlib_system.nim.c */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <setjmp.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <signal.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct Exception Exception;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TSafePoint TSafePoint;
typedef struct GcFrameHeader GcFrameHeader;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_ReraiseDefect__E0L0wGYS1gPD81VLstNO2g tyObject_ReraiseDefect__E0L0wGYS1gPD81VLstNO2g;
typedef struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ;
typedef struct tyObject_ArithmeticDefect__cT9c9bHlHSpA1QTnKbHjnIkA tyObject_ArithmeticDefect__cT9c9bHlHSpA1QTnKbHjnIkA;
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9axCnCRMUx32AHzFgBrzSMg) (Exception* e);
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef N_NIMCALL_PTR(void, tyProc__NFmM6mqUOVW3cJg4yvk8Fw) (Exception* e);
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, tyProc__W6IXMh2CA4X1rFYGjUb4yg) (NimStringDesc* msg);
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
};
struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA {
  Exception Sup;
};
struct tyObject_ReraiseDefect__E0L0wGYS1gPD81VLstNO2g {
  tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA Sup;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_ArithmeticDefect__cT9c9bHlHSpA1QTnKbHjnIkA {
  tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA Sup;
};
struct tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ {
  tyObject_ArithmeticDefect__cT9c9bHlHSpA1QTnKbHjnIkA Sup;
};
typedef N_NOCONV_PTR(void, tyProc__ZEo3s9cIqJYP74f7GMZM2FA) (int a);
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NOCONV(void, signalHandler)(int sign);
N_LIB_PRIVATE N_NIMCALL(void, showErrorMessage_system_2525)(NCSTRING data, NI length);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, toNimStr)(NCSTRING str, NI len);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewStringNoInit)(NI space);
N_LIB_PRIVATE N_NIMCALL(void*, newObjNoInit_system_3715)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NOCONV(void*, allocImpl_system_1732)(NI size);
static N_INLINE(void, copyMem_system_1716)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
static N_INLINE(NI, nimCStrLen)(NCSTRING a);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void);
static N_INLINE(void, sysFatal_system_2887)(NimStringDesc* message) __attribute__((noreturn));
N_LIB_PRIVATE N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl_system_1734)(NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem_systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(NI, align_system_1624)(NI address, NI alignment);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, sysFatal_system_3341)(NimStringDesc* message) __attribute__((noreturn));
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res);
static N_INLINE(NI, resize_system_3809)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, dataPointer_system_3799)(TGenericSeq* a, NI elemAlign);
static N_INLINE(NI, pluspercent__system_696)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionAux_system_2855)(Exception* e);
static N_INLINE(void, pushCurrentException)(Exception* e);
N_LIB_PRIVATE N_NIMCALL(void, reportUnhandledError_system_2844)(Exception* e);
N_LIB_PRIVATE N_NIMCALL(void, writeToStdErr_system_2520)(NCSTRING msg, NI length);
static N_INLINE(void, rawWriteString)(FILE* f, NCSTRING s, NI length);
N_LIB_PRIVATE N_NIMCALL(void, registerSignalHandler_system_2972)(void);
N_LIB_PRIVATE TNimType NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_;
N_LIB_PRIVATE TNimType NTIexception__XEycrCsme5C8CVWAYEcdBQ_;
N_LIB_PRIVATE TNimType NTIrefexception__vU9aO9cTqOMn6CBzhV8rX7Sw_;
N_LIB_PRIVATE TNimType NTIcstring__S9agCYBinaYZnGWcjTdxclg_;
N_LIB_PRIVATE TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
N_LIB_PRIVATE TNimType NTIstacktraceentry__oLyohQ7O2XOvGnflOss8EA_;
N_LIB_PRIVATE TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTIseqLstacktraceentryT__uB9b75OUPRENsBAu4AnoePA_;
N_LIB_PRIVATE TNimType NTIdefect__LbeSGvgPzGzXnW9caIkJqMA_;
N_LIB_PRIVATE TNimType NTIreraisedefect__E0L0wGYS1gPD81VLstNO2g_;
N_LIB_PRIVATE TNimType NTIrefreraisedefect__uG62cfJZ15c2siK3CKLmnQ_;
N_LIB_PRIVATE TNimType NTIarithmeticdefect__cT9c9bHlHSpA1QTnKbHjnIkA_;
N_LIB_PRIVATE TNimType NTIoverflowdefect__9cxMi1BPLc3UKt9br86bGfGQ_;
N_LIB_PRIVATE TNimType NTIrefoverflowdefect__r8GBEWywN07B3Rat3azS4Q_;
STRING_LITERAL(TM__Q5wkpxktOdTGvlSRo9bzt9aw_6, "over- or underflow", 18);
STRING_LITERAL(TM__Q5wkpxktOdTGvlSRo9bzt9aw_9, "no exception to reraise", 23);
N_LIB_PRIVATE NI nim_program_result;
N_LIB_PRIVATE tyProc__9axCnCRMUx32AHzFgBrzSMg globalRaiseHook_system_2280;
N_LIB_PRIVATE tyProc__9axCnCRMUx32AHzFgBrzSMg localRaiseHook_system_2283;
N_LIB_PRIVATE tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ outOfMemHook_system_2285;
N_LIB_PRIVATE tyProc__NFmM6mqUOVW3cJg4yvk8Fw unhandledExceptionHook_system_2288;
N_LIB_PRIVATE TNimType strDesc_system_2401 = {((NI) 4), 0, ((tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A) 28), 2, NIM_NIL, NIM_NIL, NIM_NIL, NIM_NIL, NIM_NIL}
;
N_LIB_PRIVATE tyProc__W6IXMh2CA4X1rFYGjUb4yg errorMessageWriter_system_2517;
N_LIB_PRIVATE TFrame* framePtr_system_2553;
N_LIB_PRIVATE TSafePoint* excHandler_system_2554;
N_LIB_PRIVATE Exception* currException_system_2555;
N_LIB_PRIVATE GcFrameHeader* gcFramePtr_system_2556;
N_LIB_PRIVATE tyProc__W6IXMh2CA4X1rFYGjUb4yg onUnhandledException_system_2740;
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).prev = excHandler_system_2554;
	excHandler_system_2554 = s;
}
N_LIB_PRIVATE N_NOCONV(void*, allocImpl_system_1732)(NI size) {
	void* result;
	result = (void*)0;
	result = malloc(((size_t) (size)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, newObjNoInit_system_3715)(TNimType* typ, NI size) {
	void* result;
	result = (void*)0;
	result = allocImpl_system_1732(((NI) (size)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewStringNoInit)(NI space) {
	NimStringDesc* result;
	NI s;
	void* T5_;
	result = (NimStringDesc*)0;
	s = space;
	{
		if (!(s < ((NI) 7))) goto LA3_;
		s = ((NI) 7);
	}
	LA3_: ;
	T5_ = (void*)0;
	T5_ = newObjNoInit_system_3715((&strDesc_system_2401), (NI)((NI)(((NI) 8) + s) + ((NI) 1)));
	result = ((NimStringDesc*) (T5_));
	(*result).Sup.reserved = s;
	(*result).Sup.len = ((NI) 0);
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem_system_1716)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, toNimStr)(NCSTRING str, NI len) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	result = rawNewStringNoInit(len);
	(*result).Sup.len = len;
	copyMem_system_1716(((void*) ((*result).data)), ((void*) (str)), ((NI) ((NI)(len + ((NI) 1)))));
	return result;
}
static N_INLINE(NI, nimCStrLen)(NCSTRING a) {
	NI result;
	size_t T1_;
	result = (NI)0;
	T1_ = (size_t)0;
	T1_ = strlen(a);
	result = ((NI) (T1_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	{
		if (!(((void*) (str)) == NIM_NIL)) goto LA3_;
		result = ((NimStringDesc*) NIM_NIL);
	}
	goto LA1_;
	LA3_: ;
	{
		result = toNimStr(str, (str ? nimCStrLen(str) : 0));
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, popSafePoint)(void) {
	excHandler_system_2554 = (*excHandler_system_2554).prev;
}
static N_INLINE(void, popCurrentException)(void) {
	currException_system_2555 = (*currException_system_2555).up;
}
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl_system_1734)(NI size) {
	void* result;
	result = (void*)0;
	result = calloc(((size_t) (size)), ((size_t) 1));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, newObj)(TNimType* typ, NI size) {
	void* result;
	result = (void*)0;
	result = alloc0Impl_system_1734(((NI) (size)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		{
			if (!!(((NI)((*src).Sup.reserved & ((NI) (-2147483647 -1))) == ((NI) 0)))) goto LA7_;
			result = src;
		}
		goto LA5_;
		LA7_: ;
		{
			result = rawNewStringNoInit((*src).Sup.len);
			(*result).Sup.len = (*src).Sup.len;
			copyMem_system_1716(((void*) ((*result).data)), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		}
		LA5_: ;
	}
	LA3_: ;
	return result;
}
static N_INLINE(void, nimSetMem_systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem_systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) - (NU32)(((NU) (b))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(r ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(r ^ (NI)((NU32) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		(*res) = r;
	}
	goto LA1_;
	LA5_: ;
	{
		result = NIM_TRUE;
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, sysFatal_system_3341)(NimStringDesc* message) {
	tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ* T1_;
	T1_ = (tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ*)0;
	T1_ = (tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ*) newObj((&NTIrefoverflowdefect__r8GBEWywN07B3Rat3azS4Q_), sizeof(tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ));
	(*T1_).Sup.Sup.Sup.Sup.m_type = (&NTIoverflowdefect__9cxMi1BPLc3UKt9br86bGfGQ_);
	(*T1_).Sup.Sup.Sup.name = "OverflowDefect";
	(*T1_).Sup.Sup.Sup.message = copyString(message);
	raiseExceptionEx((Exception*)T1_, "OverflowDefect", "sysFatal", "/home/rad/.choosenim/toolchains/nim-1.6.0/lib/system/fatal.nim", 53);
}
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void) {
	sysFatal_system_3341(((NimStringDesc*) &TM__Q5wkpxktOdTGvlSRo9bzt9aw_6));
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) + (NU32)(((NU) (b))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(r ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(r ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		(*res) = r;
	}
	goto LA1_;
	LA5_: ;
	{
		result = NIM_TRUE;
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, align_system_1624)(NI address, NI alignment) {
	NI result;
	result = (NI)0;
	{
		if (!(alignment == ((NI) 0))) goto LA3_;
		result = address;
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_5;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_7;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_8;
		if (nimSubInt(alignment, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_5)) { raiseOverflow(); };
		if (nimAddInt(address, (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_5), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_7)) { raiseOverflow(); };
		if (nimSubInt(alignment, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_8)) { raiseOverflow(); };
		result = (NI)((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_7) & (NI)((NU32) ~((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_8))));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, newSeq)(TNimType* typ, NI len) {
	void* result;
	NI T1_;
	result = (void*)0;
	T1_ = (NI)0;
	T1_ = align_system_1624(((NI) 8), (*typ).align);
	result = newObj(typ, (NI)(T1_ + (NI)(len * (*(*typ).base).size)));
	(*((TGenericSeq*) (result))).len = len;
	(*((TGenericSeq*) (result))).reserved = len;
	return result;
}
static N_INLINE(NI, resize_system_3809)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, pluspercent__system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) + (NU32)(((NU) (y))))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, dataPointer_system_3799)(TGenericSeq* a, NI elemAlign) {
	void* result;
	NI T1_;
	NI T2_;
	result = (void*)0;
	T1_ = (NI)0;
	T1_ = align_system_1624(((NI) 8), elemAlign);
	T2_ = (NI)0;
	T2_ = pluspercent__system_696(((NI) (ptrdiff_t) (a)), T1_);
	result = ((void*) (T2_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	{
		void* T5_;
		if (!(s == ((TGenericSeq*) NIM_NIL))) goto LA3_;
		T5_ = (void*)0;
		T5_ = newSeq(typ, ((NI) 1));
		result = ((TGenericSeq*) (T5_));
		(*result).len = ((NI) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		result = s;
		{
			NI r;
			void* T11_;
			void* T12_;
			void* T13_;
			if (!((NI)((*result).reserved & ((NI) 1073741823)) <= (*result).len)) goto LA9_;
			r = resize_system_3809((NI)((*result).reserved & ((NI) 1073741823)));
			T11_ = (void*)0;
			T11_ = newSeq(typ, r);
			result = ((TGenericSeq*) (T11_));
			(*result).len = (*s).len;
			T12_ = (void*)0;
			T12_ = dataPointer_system_3799(result, (*(*typ).base).align);
			T13_ = (void*)0;
			T13_ = dataPointer_system_3799(s, (*(*typ).base).align);
			copyMem_system_1716(T12_, T13_, ((NI) ((NI)((*s).len * (*(*typ).base).size))));
			(*s).len = ((NI) 0);
		}
		LA9_: ;
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, pushCurrentException)(Exception* e) {
	(*e).up = currException_system_2555;
	currException_system_2555 = e;
}
N_LIB_PRIVATE N_NIMCALL(void, reportUnhandledError_system_2844)(Exception* e) {
	{
		if (!!((unhandledExceptionHook_system_2288 == NIM_NIL))) goto LA3_;
		unhandledExceptionHook_system_2288(e);
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionAux_system_2855)(Exception* e) {
{	{
		if (!!((localRaiseHook_system_2283 == NIM_NIL))) goto LA3_;
		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = localRaiseHook_system_2283(e);
			if (!!(T7_)) goto LA8_;
			goto BeforeRet_;
		}
		LA8_: ;
	}
	LA3_: ;
	{
		if (!!((globalRaiseHook_system_2280 == NIM_NIL))) goto LA12_;
		{
			NIM_BOOL T16_;
			T16_ = (NIM_BOOL)0;
			T16_ = globalRaiseHook_system_2280(e);
			if (!!(T16_)) goto LA17_;
			goto BeforeRet_;
		}
		LA17_: ;
	}
	LA12_: ;
	{
		if (!!((excHandler_system_2554 == ((TSafePoint*) NIM_NIL)))) goto LA21_;
		pushCurrentException(e);
		longjmp((*excHandler_system_2554).context, ((int) 1));
	}
	goto LA19_;
	LA21_: ;
	{
		reportUnhandledError_system_2844(e);
		exit(((NI) 1));
	}
	LA19_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line) {
	{
		if (!((*e).name == 0)) goto LA3_;
		(*e).name = ename;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA T11_;
		NI T12_;
		T7_ = (NIM_BOOL)0;
		T7_ = !((((void*) (procname)) == NIM_NIL));
		if (!(T7_)) goto LA8_;
		T7_ = !((((void*) (filename)) == NIM_NIL));
		LA8_: ;
		if (!T7_) goto LA9_;
		nimZeroMem((void*)(&T11_), sizeof(tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA));
		T11_.procname = procname;
		T11_.filename = filename;
		T11_.line = line;
		(*e).trace = (tySequence__uB9b75OUPRENsBAu4AnoePA*) incrSeqV3((TGenericSeq*)((*e).trace), (&NTIseqLstacktraceentryT__uB9b75OUPRENsBAu4AnoePA_));
		T12_ = (*e).trace->Sup.len++;
		(*e).trace->data[T12_] = T11_;
	}
	LA9_: ;
	raiseExceptionAux_system_2855(e);
}
static N_INLINE(void, sysFatal_system_2887)(NimStringDesc* message) {
	tyObject_ReraiseDefect__E0L0wGYS1gPD81VLstNO2g* T1_;
	T1_ = (tyObject_ReraiseDefect__E0L0wGYS1gPD81VLstNO2g*)0;
	T1_ = (tyObject_ReraiseDefect__E0L0wGYS1gPD81VLstNO2g*) newObj((&NTIrefreraisedefect__uG62cfJZ15c2siK3CKLmnQ_), sizeof(tyObject_ReraiseDefect__E0L0wGYS1gPD81VLstNO2g));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIreraisedefect__E0L0wGYS1gPD81VLstNO2g_);
	(*T1_).Sup.Sup.name = "ReraiseDefect";
	(*T1_).Sup.Sup.message = copyString(message);
	raiseExceptionEx((Exception*)T1_, "ReraiseDefect", "sysFatal", "/home/rad/.choosenim/toolchains/nim-1.6.0/lib/system/fatal.nim", 53);
}
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void) {
	{
		if (!(currException_system_2555 == ((Exception*) NIM_NIL))) goto LA3_;
		sysFatal_system_2887(((NimStringDesc*) &TM__Q5wkpxktOdTGvlSRo9bzt9aw_9));
	}
	goto LA1_;
	LA3_: ;
	{
		raiseExceptionAux_system_2855(currException_system_2555);
	}
	LA1_: ;
}
static N_INLINE(void, rawWriteString)(FILE* f, NCSTRING s, NI length) {
	int T1_;
	int T2_;
	T1_ = (int)0;
	T1_ = fwrite(((void*) (s)), ((size_t) 1), ((size_t) (length)), f);
	(void)(T1_);
	T2_ = (int)0;
	T2_ = fflush(f);
	(void)(T2_);
}
N_LIB_PRIVATE N_NIMCALL(void, writeToStdErr_system_2520)(NCSTRING msg, NI length) {
	rawWriteString(stderr, msg, length);
}
N_LIB_PRIVATE N_NIMCALL(void, showErrorMessage_system_2525)(NCSTRING data, NI length) {
	NIM_BOOL volatile toWrite;
	toWrite = NIM_TRUE;
	{
		TSafePoint TM__Q5wkpxktOdTGvlSRo9bzt9aw_2;
		NimStringDesc* T5_;
		if (!!((errorMessageWriter_system_2517 == NIM_NIL))) goto LA3_;
		pushSafePoint(&TM__Q5wkpxktOdTGvlSRo9bzt9aw_2);
		TM__Q5wkpxktOdTGvlSRo9bzt9aw_2.status = setjmp(TM__Q5wkpxktOdTGvlSRo9bzt9aw_2.context);
		if (TM__Q5wkpxktOdTGvlSRo9bzt9aw_2.status == 0) {
		T5_ = (NimStringDesc*)0;
		T5_ = cstrToNimstr(data);
		errorMessageWriter_system_2517(T5_);
		toWrite = NIM_FALSE;
		popSafePoint();
		}
		else {
			popSafePoint();
			{
				TM__Q5wkpxktOdTGvlSRo9bzt9aw_2.status = 0;
				popCurrentException();
			}
		}
		if (TM__Q5wkpxktOdTGvlSRo9bzt9aw_2.status != 0) reraiseException();
	}
	LA3_: ;
	{
		if (!toWrite) goto LA10_;
		writeToStdErr_system_2520(data, length);
	}
	LA10_: ;
}
N_LIB_PRIVATE N_NOCONV(void, signalHandler)(int sign) {
	NCSTRING msg;
	msg = (NCSTRING)0;
	{
		if (!(sign == SIGINT)) goto LA3_;
		msg = "SIGINT: Interrupted by Ctrl-C.\012";
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(sign == SIGSEGV)) goto LA6_;
		msg = "SIGSEGV: Illegal storage access. (Attempt to read from nil\?)\012";
	}
	goto LA1_;
	LA6_: ;
	{
		if (!(sign == SIGABRT)) goto LA9_;
		msg = "SIGABRT: Abnormal termination.\012";
	}
	goto LA1_;
	LA9_: ;
	{
		if (!(sign == SIGFPE)) goto LA12_;
		msg = "SIGFPE: Arithmetic error.\012";
	}
	goto LA1_;
	LA12_: ;
	{
		if (!(sign == SIGILL)) goto LA15_;
		msg = "SIGILL: Illegal operation.\012";
	}
	goto LA1_;
	LA15_: ;
	{
		if (!NIM_FALSE) goto LA18_;
		msg = "SIGBUS: Illegal storage access. (Attempt to read from nil\?)\012";
	}
	goto LA1_;
	LA18_: ;
	{
		{
			msg = "unknown signal\012";
		}
	}
	LA1_: ;
	showErrorMessage_system_2525(msg, (msg ? nimCStrLen(msg) : 0));
	exit(((NI) 1));
}
N_LIB_PRIVATE N_NIMCALL(void, registerSignalHandler_system_2972)(void) {
	tyProc__ZEo3s9cIqJYP74f7GMZM2FA T1_;
	tyProc__ZEo3s9cIqJYP74f7GMZM2FA T2_;
	tyProc__ZEo3s9cIqJYP74f7GMZM2FA T3_;
	tyProc__ZEo3s9cIqJYP74f7GMZM2FA T4_;
	tyProc__ZEo3s9cIqJYP74f7GMZM2FA T5_;
	T1_ = (tyProc__ZEo3s9cIqJYP74f7GMZM2FA)0;
	T1_ = signal(SIGINT, signalHandler);
	T2_ = (tyProc__ZEo3s9cIqJYP74f7GMZM2FA)0;
	T2_ = signal(SIGSEGV, signalHandler);
	T3_ = (tyProc__ZEo3s9cIqJYP74f7GMZM2FA)0;
	T3_ = signal(SIGABRT, signalHandler);
	T4_ = (tyProc__ZEo3s9cIqJYP74f7GMZM2FA)0;
	T4_ = signal(SIGFPE, signalHandler);
	T5_ = (tyProc__ZEo3s9cIqJYP74f7GMZM2FA)0;
	T5_ = signal(SIGILL, signalHandler);
}
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void) {
{
	registerSignalHandler_system_2972();
}
}

N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void) {
static TNimNode* TM__Q5wkpxktOdTGvlSRo9bzt9aw_3_5[5];
static TNimNode* TM__Q5wkpxktOdTGvlSRo9bzt9aw_4_3[3];
static TNimNode TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[15];
NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_.size = sizeof(RootObj);
NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_.align = NIM_ALIGNOF(RootObj);
NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_.kind = 17;
NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_.base = 0;
NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_.flags = 1;
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[0].len = 0; TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[0].kind = 2;
NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_.node = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[0];
NTIexception__XEycrCsme5C8CVWAYEcdBQ_.size = sizeof(Exception);
NTIexception__XEycrCsme5C8CVWAYEcdBQ_.align = NIM_ALIGNOF(Exception);
NTIexception__XEycrCsme5C8CVWAYEcdBQ_.kind = 17;
NTIexception__XEycrCsme5C8CVWAYEcdBQ_.base = (&NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_3_5[0] = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[2];
NTIrefexception__vU9aO9cTqOMn6CBzhV8rX7Sw_.size = sizeof(Exception*);
NTIrefexception__vU9aO9cTqOMn6CBzhV8rX7Sw_.align = NIM_ALIGNOF(Exception*);
NTIrefexception__vU9aO9cTqOMn6CBzhV8rX7Sw_.kind = 22;
NTIrefexception__vU9aO9cTqOMn6CBzhV8rX7Sw_.base = (&NTIexception__XEycrCsme5C8CVWAYEcdBQ_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[2].kind = 1;
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[2].offset = offsetof(Exception, parent);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[2].typ = (&NTIrefexception__vU9aO9cTqOMn6CBzhV8rX7Sw_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[2].name = "parent";
TM__Q5wkpxktOdTGvlSRo9bzt9aw_3_5[1] = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[3];
NTIcstring__S9agCYBinaYZnGWcjTdxclg_.size = sizeof(NCSTRING);
NTIcstring__S9agCYBinaYZnGWcjTdxclg_.align = NIM_ALIGNOF(NCSTRING);
NTIcstring__S9agCYBinaYZnGWcjTdxclg_.kind = 29;
NTIcstring__S9agCYBinaYZnGWcjTdxclg_.base = 0;
NTIcstring__S9agCYBinaYZnGWcjTdxclg_.flags = 3;
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[3].kind = 1;
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[3].offset = offsetof(Exception, name);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[3].typ = (&NTIcstring__S9agCYBinaYZnGWcjTdxclg_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[3].name = "name";
TM__Q5wkpxktOdTGvlSRo9bzt9aw_3_5[2] = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[4];
NTIstring__77mFvmsOLKik79ci2hXkHEg_.size = sizeof(NimStringDesc*);
NTIstring__77mFvmsOLKik79ci2hXkHEg_.align = NIM_ALIGNOF(NimStringDesc*);
NTIstring__77mFvmsOLKik79ci2hXkHEg_.kind = 28;
NTIstring__77mFvmsOLKik79ci2hXkHEg_.base = 0;
NTIstring__77mFvmsOLKik79ci2hXkHEg_.flags = 2;
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[4].kind = 1;
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[4].offset = offsetof(Exception, message);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[4].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[4].name = "msg";
TM__Q5wkpxktOdTGvlSRo9bzt9aw_3_5[3] = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[5];
NTIstacktraceentry__oLyohQ7O2XOvGnflOss8EA_.size = sizeof(tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA);
NTIstacktraceentry__oLyohQ7O2XOvGnflOss8EA_.align = NIM_ALIGNOF(tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA);
NTIstacktraceentry__oLyohQ7O2XOvGnflOss8EA_.kind = 18;
NTIstacktraceentry__oLyohQ7O2XOvGnflOss8EA_.base = 0;
NTIstacktraceentry__oLyohQ7O2XOvGnflOss8EA_.flags = 1;
TM__Q5wkpxktOdTGvlSRo9bzt9aw_4_3[0] = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[7];
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[7].kind = 1;
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[7].offset = offsetof(tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA, procname);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[7].typ = (&NTIcstring__S9agCYBinaYZnGWcjTdxclg_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[7].name = "procname";
TM__Q5wkpxktOdTGvlSRo9bzt9aw_4_3[1] = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[8];
NTIint__rR5Bzr1D5krxoo1NcNyeMA_.size = sizeof(NI);
NTIint__rR5Bzr1D5krxoo1NcNyeMA_.align = NIM_ALIGNOF(NI);
NTIint__rR5Bzr1D5krxoo1NcNyeMA_.kind = 31;
NTIint__rR5Bzr1D5krxoo1NcNyeMA_.base = 0;
NTIint__rR5Bzr1D5krxoo1NcNyeMA_.flags = 3;
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[8].kind = 1;
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[8].offset = offsetof(tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA, line);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[8].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[8].name = "line";
TM__Q5wkpxktOdTGvlSRo9bzt9aw_4_3[2] = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[9];
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[9].kind = 1;
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[9].offset = offsetof(tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA, filename);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[9].typ = (&NTIcstring__S9agCYBinaYZnGWcjTdxclg_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[9].name = "filename";
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[6].len = 3; TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[6].kind = 2; TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[6].sons = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_4_3[0];
NTIstacktraceentry__oLyohQ7O2XOvGnflOss8EA_.node = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[6];
NTIseqLstacktraceentryT__uB9b75OUPRENsBAu4AnoePA_.size = sizeof(tySequence__uB9b75OUPRENsBAu4AnoePA*);
NTIseqLstacktraceentryT__uB9b75OUPRENsBAu4AnoePA_.align = NIM_ALIGNOF(tySequence__uB9b75OUPRENsBAu4AnoePA*);
NTIseqLstacktraceentryT__uB9b75OUPRENsBAu4AnoePA_.kind = 24;
NTIseqLstacktraceentryT__uB9b75OUPRENsBAu4AnoePA_.base = (&NTIstacktraceentry__oLyohQ7O2XOvGnflOss8EA_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[5].kind = 1;
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[5].offset = offsetof(Exception, trace);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[5].typ = (&NTIseqLstacktraceentryT__uB9b75OUPRENsBAu4AnoePA_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[5].name = "trace";
TM__Q5wkpxktOdTGvlSRo9bzt9aw_3_5[4] = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[10];
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[10].kind = 1;
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[10].offset = offsetof(Exception, up);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[10].typ = (&NTIrefexception__vU9aO9cTqOMn6CBzhV8rX7Sw_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[10].name = "up";
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[1].len = 5; TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[1].kind = 2; TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[1].sons = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_3_5[0];
NTIexception__XEycrCsme5C8CVWAYEcdBQ_.node = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[1];
NTIdefect__LbeSGvgPzGzXnW9caIkJqMA_.size = sizeof(tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA);
NTIdefect__LbeSGvgPzGzXnW9caIkJqMA_.align = NIM_ALIGNOF(tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA);
NTIdefect__LbeSGvgPzGzXnW9caIkJqMA_.kind = 17;
NTIdefect__LbeSGvgPzGzXnW9caIkJqMA_.base = (&NTIexception__XEycrCsme5C8CVWAYEcdBQ_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[11].len = 0; TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[11].kind = 2;
NTIdefect__LbeSGvgPzGzXnW9caIkJqMA_.node = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[11];
NTIreraisedefect__E0L0wGYS1gPD81VLstNO2g_.size = sizeof(tyObject_ReraiseDefect__E0L0wGYS1gPD81VLstNO2g);
NTIreraisedefect__E0L0wGYS1gPD81VLstNO2g_.align = NIM_ALIGNOF(tyObject_ReraiseDefect__E0L0wGYS1gPD81VLstNO2g);
NTIreraisedefect__E0L0wGYS1gPD81VLstNO2g_.kind = 17;
NTIreraisedefect__E0L0wGYS1gPD81VLstNO2g_.base = (&NTIdefect__LbeSGvgPzGzXnW9caIkJqMA_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[12].len = 0; TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[12].kind = 2;
NTIreraisedefect__E0L0wGYS1gPD81VLstNO2g_.node = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[12];
NTIrefreraisedefect__uG62cfJZ15c2siK3CKLmnQ_.size = sizeof(tyObject_ReraiseDefect__E0L0wGYS1gPD81VLstNO2g*);
NTIrefreraisedefect__uG62cfJZ15c2siK3CKLmnQ_.align = NIM_ALIGNOF(tyObject_ReraiseDefect__E0L0wGYS1gPD81VLstNO2g*);
NTIrefreraisedefect__uG62cfJZ15c2siK3CKLmnQ_.kind = 22;
NTIrefreraisedefect__uG62cfJZ15c2siK3CKLmnQ_.base = (&NTIreraisedefect__E0L0wGYS1gPD81VLstNO2g_);
NTIarithmeticdefect__cT9c9bHlHSpA1QTnKbHjnIkA_.size = sizeof(tyObject_ArithmeticDefect__cT9c9bHlHSpA1QTnKbHjnIkA);
NTIarithmeticdefect__cT9c9bHlHSpA1QTnKbHjnIkA_.align = NIM_ALIGNOF(tyObject_ArithmeticDefect__cT9c9bHlHSpA1QTnKbHjnIkA);
NTIarithmeticdefect__cT9c9bHlHSpA1QTnKbHjnIkA_.kind = 17;
NTIarithmeticdefect__cT9c9bHlHSpA1QTnKbHjnIkA_.base = (&NTIdefect__LbeSGvgPzGzXnW9caIkJqMA_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[13].len = 0; TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[13].kind = 2;
NTIarithmeticdefect__cT9c9bHlHSpA1QTnKbHjnIkA_.node = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[13];
NTIoverflowdefect__9cxMi1BPLc3UKt9br86bGfGQ_.size = sizeof(tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ);
NTIoverflowdefect__9cxMi1BPLc3UKt9br86bGfGQ_.align = NIM_ALIGNOF(tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ);
NTIoverflowdefect__9cxMi1BPLc3UKt9br86bGfGQ_.kind = 17;
NTIoverflowdefect__9cxMi1BPLc3UKt9br86bGfGQ_.base = (&NTIarithmeticdefect__cT9c9bHlHSpA1QTnKbHjnIkA_);
TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[14].len = 0; TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[14].kind = 2;
NTIoverflowdefect__9cxMi1BPLc3UKt9br86bGfGQ_.node = &TM__Q5wkpxktOdTGvlSRo9bzt9aw_0[14];
NTIrefoverflowdefect__r8GBEWywN07B3Rat3azS4Q_.size = sizeof(tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ*);
NTIrefoverflowdefect__r8GBEWywN07B3Rat3azS4Q_.align = NIM_ALIGNOF(tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ*);
NTIrefoverflowdefect__r8GBEWywN07B3Rat3azS4Q_.kind = 22;
NTIrefoverflowdefect__r8GBEWywN07B3Rat3azS4Q_.base = (&NTIoverflowdefect__9cxMi1BPLc3UKt9br86bGfGQ_);
}

